// AUTO-GENERATED by publish.sh from .env — do not edit by hand.
// 修改 .env 后运行 ./publish.sh 重新生成。
window.__ENV__ = {
  AI_MODEL: "MiniMax-M3",
  OPENAI_API_KEY: "sk-cp-0m-e4Ba7tdxMeO3fzCWEkvhFGqj1hHV8CQxoTIXxfUoksFplTxMxIkMoSuBMxlJwnMM62i-hwjAhCKyq_Sln5Z2yHeaRCU7KL6ywYlhzQ-OrkxRe4H8ICNI",
  PORT: "6110",
  AI_BASE_URL: "https://api.minimaxi.com/v1",
  DEPLOY_DIR: "D:\files\items\llm-page",
  API_BASE: "",
  DEBUG: "false",
};
